[package]
name = "hindsight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
anyhow = "1.0.79"
thiserror = "1.0.56"
glm = { package = "nalgebra-glm", version = "0.18.0" }
