# fly.toml app configuration file generated for protohackers-zaiquiri-thrumming-sea-2864 on 2024-01-07T11:52:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "protohackers-zaiquiri-thrumming-sea-2864"
primary_region = "lhr"

[build]

[[services]]
  protocol = "udp"
  internal_port = 8000
  min_machines_running = 0

  [[services.ports]]
    port = 8000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
